-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 17:24:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymybuddy` DEFAULT CHARACTER SET utf8mb3 ;
USE `paymybuddy` ;

-- -----------------------------------------------------
-- Table `paymybuddy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `solde` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`bank_account` (
  `bank_account_id` INT NOT NULL AUTO_INCREMENT,
  `iban` VARCHAR(100) NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`bank_account_id`),
  UNIQUE INDEX `iban` (`iban` ASC) VISIBLE,
  INDEX `fk` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `paymybuddy`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy`.`bank_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`bank_transaction` (
  `bank_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(5,2) NOT NULL,
  `date` DATE NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `bank_account_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`bank_transaction_id`),
  INDEX `bank_account_id` (`bank_account_id` ASC) VISIBLE,
  CONSTRAINT `bank_transaction_ibfk_1`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `paymybuddy`.`bank_account` (`bank_account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy`.`connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`connection` (
  `connection_id` INT NOT NULL AUTO_INCREMENT,
  `user_sender_id` INT NOT NULL,
  `user_receiver_id` INT NOT NULL,
  PRIMARY KEY (`connection_id`),
  INDEX `user_sender_id` (`user_sender_id` ASC) VISIBLE,
  INDEX `user_receiver_id` (`user_receiver_id` ASC) VISIBLE,
  CONSTRAINT `connection_ibfk_1`
    FOREIGN KEY (`user_sender_id`)
    REFERENCES `paymybuddy`.`user` (`user_id`),
  CONSTRAINT `connection_ibfk_2`
    FOREIGN KEY (`user_receiver_id`)
    REFERENCES `paymybuddy`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(5,2) NOT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `user_sender_id` INT NULL DEFAULT NULL,
  `user_receiver_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `id` (`transaction_id` ASC) VISIBLE,
  UNIQUE INDEX `transaction_id` (`transaction_id` ASC) VISIBLE,
  INDEX `user_sender_id` (`user_sender_id` ASC) VISIBLE,
  INDEX `user_receiver_id` (`user_receiver_id` ASC) VISIBLE,
  CONSTRAINT `transaction_ibfk_1`
    FOREIGN KEY (`user_sender_id`)
    REFERENCES `paymybuddy`.`connection` (`user_sender_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_2`
    FOREIGN KEY (`user_receiver_id`)
    REFERENCES `paymybuddy`.`connection` (`user_receiver_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
